// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated automatically during the build by Directory.Build.targets.
//     Do not edit manually.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("0.1.0.3")]
[assembly: AssemblyFileVersion("0.1.0.3")]
